baseURL = "https://majestic-kheer-b3592c.netlify.app/"
languageCode = "en-us"
title = "Tushars Blogs"
theme = "hugo-ink"
paginate = 5

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true
enableGitInfo = true

[params]
	subtitle = "[Tushar](https://champ96k.github.io/), A place to log my thoughts"

	# Optional 64x64 avatar image.
	avatar = "https://iili.io/ZTC1jt.png"

	# # Content types to disable Disqus on.
	# disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[[menu.main]]
name = "About"
url = "/about"
weight = 5


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/champ96k"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/champ_96k"

[[params.social]]
name = "portfolio"
icon = "github"
url = "https://champ96k.github.io"

[[params.social]]
name = "portfolio"
icon = "linkedin"
url = "https://www.linkedin.com/in/tushar-nikam-a29a97131/"

[taxonomies]
   tag = "tags"